### ISSUE TITLE
PCB layout and assembly installation layout

### ISSUE THREAD

**Issue by umalave** [ProjectsWithRed/auto-wire-stripper-cutter#1]
Hi, do you have a PCB layout for this project? also, do you have the layout where you attached the threaded insert on the wood board?

**Comment by ProjectsWithRed** [comment]
Hi,

I did not create a PCB layout for this project.

Regarding the assembly layout, I just added a PDF (ee4eb457c4b8973d444eb9b3b2031fe7ea3d9ca9) showing the assembly layout. However, I recommend using it only for reference on roughly where you should fix the components to the board. I don't suggest using this for exact measurements as you should position the components where it is appropriate for your version of the project.
