### ISSUE TITLE
No display

### ISSUE THREAD

**Issue by AV1987** [ProjectsWithRed/auto-wire-stripper-cutter#11]
Hi @ProjectsWithRed.
Thanks for sharing this project, very interesting.
It seems I uploaded the code sucessful but I have no display. I only connect ESP32 Devkit with Oled 128x64.
The example code works ok with display. What do I miss?
Thank you

Tips: adding a 10uF Cap on RST pin to ground to avoid holding the Reset button during sketching.

**Comment by ProjectsWithRed** [comment]
I have updated the code since there was an update to the `Encoder` library which made it not work. Upload again and let me know if you still have issues.

**Comment by AV1987** [comment]
@ProjectsWithRed
Thank you. My display works now. But none of the motor runs and pulling 1.7A. It's hot the driver. Do you have this problem? I checked the wiring 2B,2A,1B,1A are correct and Calibration is false by default of your updated sketch.

**Comment by AV1987** [comment]
> @AV1987 I have updated the code since there was an update to the `Encoder` library which made it not work. Upload again and let me know if you still have issues.

Thanks Red! My setup is running now. Will give you update.

**Comment by AV1987** [comment]
Hi @ProjectsWithRed

I have everything is running now with your original updated code. However, the linear motion is running very slow and dragging not like your youtube video.
Please advise. Thanks
