### ISSUE TITLE
Printable baseplate with heat set inserts

### ISSUE THREAD

**Issue by fryertruck** [ProjectsWithRed/auto-wire-stripper-cutter#2]
I really appreciate your work in this project and thinking about building one. 

What do you think about adding a printable base to your project? Of course the positions would then be fixed, but I don't see an Issue with that. 

I can help you out with creating the file, but need correct measurements for that.

**Comment by ProjectsWithRed** [comment]
I have uploaded a file `assembly_layout.pdf` that shows all the measurements on the board, feel free do make a printable base 👍🏼.
