### ISSUE TITLE
Let the machine remove part of the Insulation

### ISSUE THREAD

**Issue by fryertruck** [ProjectsWithRed/auto-wire-stripper-cutter#3]
Is it possible that the machine also directly removes the insulation from the front part of the cable? Before the blade goes up again, the extruder would have to pull back for this in the first step. 

Can you perhaps test this?

**Comment by ProjectsWithRed** [comment]
You can easily achieve this with minimal changes to the code and if done correctly should work with no issues. Feel free to experiement, as I unfortunately don't have time to do it.

**Comment by ProjectsWithRed** [comment]
Inactive.
